import './globals.css'
import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'

const nunitoSans = Nunito_Sans({ subsets: ['latin'] })

import { Header } from '@/components/Header'

export const metadata: Metadata = {
  title: 'Next JS country App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
